---
- name: set facts for mesos-slave
  set_fact: mesos_slave_host_dir=/srv/services/mesos-slave

- name: create directories for mesos-slave
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ mesos_slave_host_dir }}"
    - "{{ mesos_slave_work_dir }}"
    - "{{ mesos_slave_log_dir }}"
    - "{{ mesos_slave_tmp_dir }}"

- name: create a symbolic link for mesos-slave work directory
  file: src="{{ mesos_slave_work_dir }}" dest="{{ mesos_slave_host_dir }}/work" state=link

- name: create a symbolic link for mesos-slave log directory
  file: src="{{ mesos_slave_log_dir }}" dest="{{ mesos_slave_host_dir }}/log" state=link

- name: create a symbolic link for mesos-slave tmp directory
  file: src="{{ mesos_slave_tmp_dir }}" dest="{{ mesos_slave_host_dir }}/tmp" state=link

- name: add container to whitelist
  set_fact: docker_containers_whitelist="{{ docker_containers_whitelist }} + [ 'slave-mesos' ]"
  tags: always

- name: ensure mesos-slave container is running
  docker_container:
    name: slave-mesos
    image: mesosphere/mesos-slave:1.1.0-2.0.107.ubuntu1404
    state: started
    restart_policy: unless-stopped
    privileged: yes
    network_mode: host
    log_driver: json-file
    volumes:
      - "{{ mesos_slave_host_dir }}/work:{{ mesos_slave_host_dir }}/work"
      - "{{ mesos_slave_host_dir }}/log:/log"
      - "{{ mesos_slave_host_dir }}/tmp:/tmp"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/etc/selinux/targeted/policy/policy.29:/etc/selinux/targeted/policy/policy.29"
#      - "/etc/sysconfig/docker:/etc/sysconfig/docker"
      - "/usr/lib64/libsystemd.so.0:/lib/x86_64-linux-gnu/libsystemd.so.0"
      - "/usr/lib64/libseccomp.so.2:/usr/lib/x86_64-linux-gnu/libseccomp.so.2:ro"
      - "/usr/lib64/libdevmapper.so.1.02:/lib/x86_64-linux-gnu/libdevmapper.so.1.02:ro"
      - "/usr/lib64/libdw.so.1:/lib/x86_64-linux-gnu/libdw.so.1:ro"
      - "/usr/lib64/libelf.so.1:/lib/x86_64-linux-gnu/libelf.so.1:ro"
    command: 'mesos-slave --executor_registration_timeout=3mins --ip={{ net_internal_ip }} --port={{ mesos_slave_port }} --no-hostname_lookup --master=zk://{{ zookeeper_hosts }}/mesos --no-switch_user --gc_delay=1days --gc_disk_headroom=0.4 --disk_watch_interval=10mins --containerizers=docker,mesos --image_providers=docker --isolation=docker/runtime,disk/du,filesystem/linux,cgroups/cpu,cgroups/mem --docker_registry={{ docker_registry_url }} --work_dir={{ mesos_slave_host_dir }}/work --log_dir=/log --resources=cpus:16'
