---

- name: start_processor
  docker_container:
    name: processor
    state: started
    restart_policy: unless-stopped
    network_mode: host
    log_driver: json-file
    pull: yes
    image: "{{ spark_mesos_image }}"
    command: "/spark/bin/spark-submit --master mesos://zk://{{ zookeeper_hosts }}/mesos --class com.libertyglobal.medm.NetworkLatencyProcessor --driver-memory {{ spark_task_processor_driver_memory }} --executor-memory {{ spark_task_processor_executor_memory }} --num-executors {{ spark_task_processor_num_executors }} --executor-cores {{ spark_task_processor_executor_cores }} /scripts/spark-reports-assembly-0.6-SNAPSHOT.jar"
    volumes:
      - /srv/services/hadoop/conf:/hadoop/conf:ro
      - /srv/services/spark/conf:/spark/conf:ro
      - /srv/services/spark/conf/hosts:/etc/hosts:ro
    env:
      PROCESSOR_KAFKA_SERVERS: "{{ kafka_hosts }}"
      SPARKIMAGE: "{{ spark_mesos_image }}"
      ADDITIONALVOLUMES: "/srv/services/hadoop/conf:/hadoop/conf:ro,/srv/services/spark/conf:/spark/conf:ro,/srv/services/spark/conf/hosts:/etc/hosts:ro"
