---
- name: set facts for kibana
  set_fact:
    kibana_host_dir: /srv/services/kibana

- name: Create target directory
  file: path="{{ item }}" state=directory mode=0755 owner=1000 group=1000
  with_items:
    - "{{ kibana_host_dir }}"
    - "{{ kibana_conf_dir }}"
    - "{{ kibana_log_dir }}"
    - "{{ kibana_tmp_dir }}"

- name: create a symbolic link for conf directory of kibana
  file: src="{{ kibana_conf_dir }}" dest="{{ kibana_host_dir }}/conf" state=link

- name: create a symbolic link for tmp directory of kibana
  file: src="{{ kibana_tmp_dir }}"  dest="{{ kibana_host_dir }}/tmp"  state=link

- name: create a symbolic link for log directory of kibana
  file: src="{{ kibana_log_dir }}"  dest="{{ kibana_host_dir }}/log"  state=link

- name: copy configuration
  template: src=kibana.yml.j2 dest="{{ kibana_host_dir }}/conf/kibana.yml" force=yes

- name: start kibana
  vars:
    volumes:
      - "{{ kibana_host_dir }}/conf:/etc/kibana/conf.d"
      - "{{ kibana_host_dir }}/tmp:/tmp"
      - "{{ kibana_host_dir }}/log:/var/log"
  docker_container:
    name: kibana
    state: started
    restart_policy: unless-stopped
    image: docker.elastic.co/kibana/kibana:5.2.2
    network_mode: host
    log_driver: json-file
    recreate: yes
    exposed_ports:
      - "{{ kibana_port }}"
    published_ports:
      - "{{ kibana_port }}:{{ kibana_port }}"
    volumes:
      "{{ volumes }}"
    command: "kibana -c /etc/kibana/conf.d/kibana.yml"
