---
- name: set facts for statsd
  set_fact: statsd_host_dir=/srv/services/statsd

- name: create directories for statsd
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ statsd_host_dir }}"
    - "{{ statsd_conf_dir }}"

- name: link conf dir to host dir
  file: src="{{ statsd_conf_dir }}" dest="{{ statsd_host_dir }}/conf" state=link force=yes

- name: set environment variables
  template: src=templates/statsd-config.js.j2 dest="{{ statsd_host_dir }}/conf/config.js"
  notify: restart statsd

- meta: flush_handlers

- name: add container to whitelist
  set_fact: docker_containers_whitelist="{{ docker_containers_whitelist }} + [ 'statsd' ]"
  tags: always

- name: start statsd
  docker_container:
    name: statsd
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ statsd_host_dir }}/conf/config.js:/opt/statsd/config.js"
    image: "{{ docker_registry }}/lgi/statsd:1.2"
    recreate: "{{ statsd_restart_docker|default('no') }}"
    network_mode: host
    log_driver: json-file
