---

- modprobe:
    name: nf_conntrack
    state: present

- name: enable conntrack kernel module
  modprobe: name={{ item }} state=present
  with_items:
    - nf_conntrack
    - nf_conntrack_ipv4
    - nf_nat_masquerade_ipv4
    - nf_nat
    - nf_nat_ipv4
    - nf_defrag_ipv4

- name: Set sysctl settings accordingly
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present sysctl_set=yes
  with_items:
    - name: net.ipv4.ip_nonlocal_bind
      value: 1
    - name: net.nf_conntrack_max
      value: 4194304
    - name: net.netfilter.nf_conntrack_generic_timeout
      value: 60
    - name: net.netfilter.nf_conntrack_tcp_timeout_established
      value: 3600
    - name: net.core.optmem_max
      value: 1048576
    - name: net.core.wmem_max
      value: 33554432
    - name: net.core.rmem_max
      value: 33554432
    - name: net.core.wmem_default
      value: 524288
    - name: net.core.rmem_default
      value: 524288
    - name: net.core.somaxconn
      value: 65534
    - name: net.ipv4.tcp_mem
      value: 131072 262144 524288
    - name: net.ipv4.udp_mem
      value: 4096 32768 262144
    - name: net.ipv4.tcp_rmem
      value: 4096 16060 64060
    - name: net.ipv4.tcp_wmem
      value: 4096 16384 262144
    - name: net.core.netdev_max_backlog
      value: 100000
    - name: net.ipv4.tcp_max_tw_buckets
      value: 131072
    - name: net.ipv4.tcp_tw_recycle
      value: 0
    - name: net.ipv4.tcp_tw_reuse
      value: 1
    - name: net.ipv4.ip_local_port_range
      value: 20000 65534
    - name: net.ipv4.tcp_max_syn_backlog
      value: 100000
    - name: vm.max_map_count
      value: 262144
    - name: vm.swappiness
      value: 1

  tags: [config, net]

#- copy: src=etc/sysfs.conf dest=/etc/sysfs.conf
#  tags: [config]
#  notify: refresh sysfs
