---

- name: install collectd
  yum:
    name: collectd
    state: present

- name: create collectd config file
  template: src=templates/collectd.conf.j2 dest="/etc/collectd.conf"
  notify: restart collectd

- name: restart collectd
  service:
    name: collectd
    state: started
    enabled: yes
